import React from "react";
import {
  AlertTriangle,
  ArrowRight,
  ArrowUpRight,
  BookOpen,
  Check,
  Download,
  ExternalLink,
  FileText,
  Flower2,
  GraduationCap,
  Image,
  Inbox,
  LayoutGrid,
  Leaf,
  Library,
  Lightbulb,
  Lock,
  LogOut,
  Mail,
  Mic,
  Package,
  Pencil,
  Plus,
  Save,
  Search,
  Settings,
  Snowflake,
  Sparkles,
  Sun,
  Trash2,
  TrendingUp,
  Users,
} from "lucide-react";

export const AdminIcon = {
  articles: BookOpen,
  products: Package,
  kajian: Mic,
  classes: GraduationCap,
  total: Library,
  subscribers: Users,
  dashboard: LayoutGrid,
  content: FileText,
  settings: Settings,
  sparkle: Sparkles,
  warning: AlertTriangle,
  logo: Sparkles,
  trend: TrendingUp,
  tip: Lightbulb,
  empty: Inbox,
  edit: Pencil,
  add: Plus,
  save: Save,
  delete: Trash2,
  check: Check,
  warm: Sun,
  cool: Snowflake,
  sage: Leaf,
  blossom: Flower2,
  mail: Mail,
  lock: Lock,
  arrow: ArrowRight,
  externalLink: ArrowUpRight,
  image: Image,
  logOut: LogOut,
  search: Search,
  download: Download,
};

export function renderAdminIcon(name, { size = 18, className, style } = {}) {
  const Component = AdminIcon[name];
  if (!Component) return null;
  return <Component size={size} className={className} style={style} />;
}
