-- AlterTable
ALTER TABLE "Article" ADD COLUMN "date" TEXT;
ALTER TABLE "Article" ADD COLUMN "time" TEXT;
ALTER TABLE "Article" ADD COLUMN "reads" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Article" ADD COLUMN "claps" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Article" ADD COLUMN "tag" TEXT;
ALTER TABLE "Article" ADD COLUMN "featured" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Article" ADD COLUMN "size" TEXT;

-- AlterTable
ALTER TABLE "Product" ADD COLUMN "originalPriceCents" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Product" ADD COLUMN "rating" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Product" ADD COLUMN "sold" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Product" ADD COLUMN "tag" TEXT;

-- AlterTable
ALTER TABLE "KajianEvent" ADD COLUMN "date" INTEGER;
ALTER TABLE "KajianEvent" ADD COLUMN "month" TEXT;
ALTER TABLE "KajianEvent" ADD COLUMN "day" TEXT;
ALTER TABLE "KajianEvent" ADD COLUMN "time" TEXT;
ALTER TABLE "KajianEvent" ADD COLUMN "attendees" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "KajianEvent" ADD COLUMN "priceCents" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "KajianEvent" ADD COLUMN "free" BOOLEAN NOT NULL DEFAULT true;

-- AlterTable
ALTER TABLE "Course" ADD COLUMN "instructor" TEXT;
ALTER TABLE "Course" ADD COLUMN "lessons" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Course" ADD COLUMN "duration" TEXT;
ALTER TABLE "Course" ADD COLUMN "students" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Course" ADD COLUMN "rating" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Course" ADD COLUMN "reviews" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Course" ADD COLUMN "originalPriceCents" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Course" ADD COLUMN "tag" TEXT;
ALTER TABLE "Course" ADD COLUMN "batch" TEXT;
ALTER TABLE "Course" ADD COLUMN "startDate" TEXT;
ALTER TABLE "Course" ADD COLUMN "startDay" TEXT;
ALTER TABLE "Course" ADD COLUMN "schedule" TEXT;
ALTER TABLE "Course" ADD COLUMN "platform" TEXT;
ALTER TABLE "Course" ADD COLUMN "slots" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Course" ADD COLUMN "slotsTaken" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Course" ADD COLUMN "statusDetail" TEXT;
ALTER TABLE "Course" ADD COLUMN "emoji" TEXT;
